project:
  type: manuscript

manuscript:
  article: index.qmd
  code-links: [repo]
  notebooks:
    - notebook: manuscripts/AGU23_poster.qmd
      title: AGU23 poster

format:
  html:
    comments:
      hypothesis: true
  # jats: default
  # pdf: default

execute:
  freeze: true

date: "2024-12-13"
doi: 10.1029/2024JA033174

citation:
  container-title: "Journal of Geophysical Research: Space Physics"
  type: article-journal
  issue: 12
  volume: 129
  page: e2024JA033174

affiliations:
  - id: ucla
    num: 1
    name: University of California, Los Angeles
    address: Department of Earth, Planetary, and Space Sciences, University of California, Los Angeles
  - id: cea
    num: 2
    name: CEA, DAM, DIF
    address: CEA, DAM, DIF, Arpajon, France
  - id: lmce
    name: Université Paris-Saclay
    num: 3
    address: Laboratoire Matière en Conditions Extrêmes, Université Paris-Saclay, CEA, Bruyères-le-Châtel, France
  - id: utd
    num: 4
    name: University of Texas at Dallas
